# KASUS PINJAMAN BANK (TUGAS 7)



# MEMPROSES DATA

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn import tree
import seaborn as sns
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

url = 'https://raw.githubusercontent.com/nuskhatulhaqqi/data_mining/main/credit_score.csv'

data = pd.read_csv(url)
data.drop(columns="Unnamed: 0",inplace=True)
data

kode_kontrak  pendapatan_setahun_juta kpr_aktif  durasi_pinjaman_bulan  \
0     AGR-000001                      295        YA                     48   
1     AGR-000011                      271        YA                     36   
2     AGR-000030                      159     TIDAK                     12   
3     AGR-000043                      210        YA                     12   
4     AGR-000049                      165     TIDAK                     36   
..           ...                      ...       ...                    ...   
895   AGR-010739                      112        YA                     48   
896   AGR-010744                      120        YA                     48   
897   AGR-010758                      166     TIDAK                     24   
898   AGR-010775                      196     TIDAK                     48   
899   AGR-010790                      204     TIDAK                     24   

     jumlah_tanggungan rata_rata_overdue  risk_rating  
0                    5      61 - 90 days            4  
1                    5      61 - 90 days            4  
2                    0       0 - 30 days            1  
3                    3      46 - 60 days            3  
4                    0      31 - 45 days            2  
..                 ...               ...          ...  
895                  5         > 90 days            5  
896                  2      46 - 60 days            3  
897                  2       0 - 30 days            1  
898                  0      31 - 45 days            2  
899                  2       0 - 30 days            1  

[900 rows x 7 columns]

In [ ]:
data_y=pd.get_dummies(data['rata_rata_overdue'])
data_y.head()

0 - 30 days  31 - 45 days  46 - 60 days  61 - 90 days  > 90 days
0            0             0             0             1          0
1            0             0             0             1          0
2            1             0             0             0          0
3            0             0             1             0          0
4            0             1             0             0          0

In [ ]:
data_join = data.join(data_y)
data_join.drop(columns="rata_rata_overdue",inplace=True)

In [ ]:
data_x=pd.get_dummies(data['kpr_aktif'])
data_x.head()

TIDAK  YA
0      0   1
1      0   1
2      1   0
3      0   1
4      1   0

In [ ]:
data_fix = data_join.join(data_x)
data_fix.drop(columns="kpr_aktif",inplace=True)
data_fix

kode_kontrak  pendapatan_setahun_juta  durasi_pinjaman_bulan  \
0     AGR-000001                      295                     48   
1     AGR-000011                      271                     36   
2     AGR-000030                      159                     12   
3     AGR-000043                      210                     12   
4     AGR-000049                      165                     36   
..           ...                      ...                    ...   
895   AGR-010739                      112                     48   
896   AGR-010744                      120                     48   
897   AGR-010758                      166                     24   
898   AGR-010775                      196                     48   
899   AGR-010790                      204                     24   

     jumlah_tanggungan  risk_rating  0 - 30 days  31 - 45 days  46 - 60 days  \
0                    5            4            0             0             0   
1                    5            4            0             0             0   
2                    0            1            1             0             0   
3                    3            3            0             0             1   
4                    0            2            0             1             0   
..                 ...          ...          ...           ...           ...   
895                  5            5            0             0             0   
896                  2            3            0             0             1   
897                  2            1            1             0             0   
898                  0            2            0             1             0   
899                  2            1            1             0             0   

     61 - 90 days  > 90 days  TIDAK  YA  
0               1          0      0   1  
1               1          0      0   1  
2               0          0      1   0  
3               0          0      0   1  
4               0          0      1   0  
..            ...        ...    ...  ..  
895             0          1      0   1  
896             0          0      0   1  
897             0          0      1   0  
898             0          0      1   0  
899             0          0      1   0  

[900 rows x 12 columns]

In [ ]:
data_risk_rating = pd.DataFrame(data_fix, columns = ['risk_rating'])
data_risk_rating.head()

risk_rating
0            4
1            4
2            1
3            3
4            2

In [ ]:
data_fix.drop(columns="risk_rating",inplace=True)
data_join_new = data_fix.join(data_risk_rating)
data_join_new

kode_kontrak  pendapatan_setahun_juta  durasi_pinjaman_bulan  \
0     AGR-000001                      295                     48   
1     AGR-000011                      271                     36   
2     AGR-000030                      159                     12   
3     AGR-000043                      210                     12   
4     AGR-000049                      165                     36   
..           ...                      ...                    ...   
895   AGR-010739                      112                     48   
896   AGR-010744                      120                     48   
897   AGR-010758                      166                     24   
898   AGR-010775                      196                     48   
899   AGR-010790                      204                     24   

     jumlah_tanggungan  0 - 30 days  31 - 45 days  46 - 60 days  61 - 90 days  \
0                    5            0             0             0             1   
1                    5            0             0             0             1   
2                    0            1             0             0             0   
3                    3            0             0             1             0   
4                    0            0             1             0             0   
..                 ...          ...           ...           ...           ...   
895                  5            0             0             0             0   
896                  2            0             0             1             0   
897                  2            1             0             0             0   
898                  0            0             1             0             0   
899                  2            1             0             0             0   

     > 90 days  TIDAK  YA  risk_rating  
0            0      0   1            4  
1            0      0   1            4  
2            0      1   0            1  
3            0      0   1            3  
4            0      1   0            2  
..         ...    ...  ..          ...  
895          1      0   1            5  
896          0      0   1            3  
897          0      1   0            1  
898          0      1   0            2  
899          0      1   0            1  

[900 rows x 12 columns]

In [ ]:
from sklearn.preprocessing import MinMaxScaler
df_for_minmax_scaler=pd.DataFrame(data_join_new, columns = ['pendapatan_setahun_juta','durasi_pinjaman_bulan','jumlah_tanggungan'])
df_for_minmax_scaler.to_numpy()
scaler = MinMaxScaler()
df_hasil_minmax_scaler=scaler.fit_transform(df_for_minmax_scaler)

In [ ]:
df_hasil_minmax_scaler = pd.DataFrame(df_hasil_minmax_scaler,columns = ['pendapatan_setahun_juta','durasi_pinjaman_bulan','jumlah_tanggungan'])
df_hasil_minmax_scaler

pendapatan_setahun_juta  durasi_pinjaman_bulan  jumlah_tanggungan
0                   0.978261               1.000000           0.833333
1                   0.873913               0.666667           0.833333
2                   0.386957               0.000000           0.000000
3                   0.608696               0.000000           0.500000
4                   0.413043               0.666667           0.000000
..                       ...                    ...                ...
895                 0.182609               1.000000           0.833333
896                 0.217391               1.000000           0.333333
897                 0.417391               0.333333           0.333333
898                 0.547826               1.000000           0.000000
899                 0.582609               0.333333           0.333333

[900 rows x 3 columns]

In [ ]:
df_drop_column_for_minmaxscaler=data_join_new.drop(['pendapatan_setahun_juta','durasi_pinjaman_bulan','jumlah_tanggungan'], axis=1)
df_drop_column_for_minmaxscaler

kode_kontrak  0 - 30 days  31 - 45 days  46 - 60 days  61 - 90 days  \
0     AGR-000001            0             0             0             1   
1     AGR-000011            0             0             0             1   
2     AGR-000030            1             0             0             0   
3     AGR-000043            0             0             1             0   
4     AGR-000049            0             1             0             0   
..           ...          ...           ...           ...           ...   
895   AGR-010739            0             0             0             0   
896   AGR-010744            0             0             1             0   
897   AGR-010758            1             0             0             0   
898   AGR-010775            0             1             0             0   
899   AGR-010790            1             0             0             0   

     > 90 days  TIDAK  YA  risk_rating  
0            0      0   1            4  
1            0      0   1            4  
2            0      1   0            1  
3            0      0   1            3  
4            0      1   0            2  
..         ...    ...  ..          ...  
895          1      0   1            5  
896          0      0   1            3  
897          0      1   0            1  
898          0      1   0            2  
899          0      1   0            1  

[900 rows x 9 columns]

In [ ]:
data_new3 = pd.concat([df_drop_column_for_minmaxscaler,df_hasil_minmax_scaler], axis=1)
data_new3

kode_kontrak  0 - 30 days  31 - 45 days  46 - 60 days  61 - 90 days  \
0     AGR-000001            0             0             0             1   
1     AGR-000011            0             0             0             1   
2     AGR-000030            1             0             0             0   
3     AGR-000043            0             0             1             0   
4     AGR-000049            0             1             0             0   
..           ...          ...           ...           ...           ...   
895   AGR-010739            0             0             0             0   
896   AGR-010744            0             0             1             0   
897   AGR-010758            1             0             0             0   
898   AGR-010775            0             1             0             0   
899   AGR-010790            1             0             0             0   

     > 90 days  TIDAK  YA  risk_rating  pendapatan_setahun_juta  \
0            0      0   1            4                 0.978261   
1            0      0   1            4                 0.873913   
2            0      1   0            1                 0.386957   
3            0      0   1            3                 0.608696   
4            0      1   0            2                 0.413043   
..         ...    ...  ..          ...                      ...   
895          1      0   1            5                 0.182609   
896          0      0   1            3                 0.217391   
897          0      1   0            1                 0.417391   
898          0      1   0            2                 0.547826   
899          0      1   0            1                 0.582609   

     durasi_pinjaman_bulan  jumlah_tanggungan  
0                 1.000000           0.833333  
1                 0.666667           0.833333  
2                 0.000000           0.000000  
3                 0.000000           0.500000  
4                 0.666667           0.000000  
..                     ...                ...  
895               1.000000           0.833333  
896               1.000000           0.333333  
897               0.333333           0.333333  
898               1.000000           0.000000  
899               0.333333           0.333333  

[900 rows x 12 columns]

In [ ]:
df_new3_without_risk_rating=data_new3.drop(['risk_rating'], axis=1)
df_new3_without_risk_rating

kode_kontrak  0 - 30 days  31 - 45 days  46 - 60 days  61 - 90 days  \
0     AGR-000001            0             0             0             1   
1     AGR-000011            0             0             0             1   
2     AGR-000030            1             0             0             0   
3     AGR-000043            0             0             1             0   
4     AGR-000049            0             1             0             0   
..           ...          ...           ...           ...           ...   
895   AGR-010739            0             0             0             0   
896   AGR-010744            0             0             1             0   
897   AGR-010758            1             0             0             0   
898   AGR-010775            0             1             0             0   
899   AGR-010790            1             0             0             0   

     > 90 days  TIDAK  YA  pendapatan_setahun_juta  durasi_pinjaman_bulan  \
0            0      0   1                 0.978261               1.000000   
1            0      0   1                 0.873913               0.666667   
2            0      1   0                 0.386957               0.000000   
3            0      0   1                 0.608696               0.000000   
4            0      1   0                 0.413043               0.666667   
..         ...    ...  ..                      ...                    ...   
895          1      0   1                 0.182609               1.000000   
896          0      0   1                 0.217391               1.000000   
897          0      1   0                 0.417391               0.333333   
898          0      1   0                 0.547826               1.000000   
899          0      1   0                 0.582609               0.333333   

     jumlah_tanggungan  
0             0.833333  
1             0.833333  
2             0.000000  
3             0.500000  
4             0.000000  
..                 ...  
895           0.833333  
896           0.333333  
897           0.333333  
898           0.000000  
899           0.333333  

[900 rows x 11 columns]

In [ ]:
data_new4 = pd.concat([df_new3_without_risk_rating,data_risk_rating], axis=1)
data_new4

kode_kontrak  0 - 30 days  31 - 45 days  46 - 60 days  61 - 90 days  \
0     AGR-000001            0             0             0             1   
1     AGR-000011            0             0             0             1   
2     AGR-000030            1             0             0             0   
3     AGR-000043            0             0             1             0   
4     AGR-000049            0             1             0             0   
..           ...          ...           ...           ...           ...   
895   AGR-010739            0             0             0             0   
896   AGR-010744            0             0             1             0   
897   AGR-010758            1             0             0             0   
898   AGR-010775            0             1             0             0   
899   AGR-010790            1             0             0             0   

     > 90 days  TIDAK  YA  pendapatan_setahun_juta  durasi_pinjaman_bulan  \
0            0      0   1                 0.978261               1.000000   
1            0      0   1                 0.873913               0.666667   
2            0      1   0                 0.386957               0.000000   
3            0      0   1                 0.608696               0.000000   
4            0      1   0                 0.413043               0.666667   
..         ...    ...  ..                      ...                    ...   
895          1      0   1                 0.182609               1.000000   
896          0      0   1                 0.217391               1.000000   
897          0      1   0                 0.417391               0.333333   
898          0      1   0                 0.547826               1.000000   
899          0      1   0                 0.582609               0.333333   

     jumlah_tanggungan  risk_rating  
0             0.833333            4  
1             0.833333            4  
2             0.000000            1  
3             0.500000            3  
4             0.000000            2  
..                 ...          ...  
895           0.833333            5  
896           0.333333            3  
897           0.333333            1  
898           0.000000            2  
899           0.333333            1  

[900 rows x 12 columns]

# NAIVE BAYES CLASSIFIER

In [ ]:
from sklearn.metrics import make_scorer, accuracy_score,precision_score
from sklearn.metrics import accuracy_score ,precision_score,recall_score,f1_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import KFold,train_test_split,cross_val_score
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

In [ ]:
X=data_new4.iloc[:,1:11].values
y=data_new4.iloc[:,11].values

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [ ]:
gaussian = GaussianNB()
gaussian.fit(X_train, y_train)
Y_pred = gaussian.predict(X_test) 
accuracy_nb=round(accuracy_score(y_test,Y_pred)* 100, 2)
acc_gaussian = round(gaussian.score(X_train, y_train) * 100, 2)

cm = confusion_matrix(y_test, Y_pred)
accuracy = accuracy_score(y_test,Y_pred)
precision =precision_score(y_test, Y_pred,average='micro')
recall =  recall_score(y_test, Y_pred,average='micro')
f1 = f1_score(y_test,Y_pred,average='micro')
print('Confusion matrix for Naive Bayes\n',cm)
print('accuracy_Naive Bayes: %.3f' %accuracy)
print('precision_Naive Bayes: %.3f' %precision)
print('recall_Naive Bayes: %.3f' %recall)
print('f1-score_Naive Bayes : %.3f' %f1)

Confusion matrix for Naive Bayes
 [[69  0  0  0  0]
 [ 0 49  0  0  0]
 [ 0  0 84  0  0]
 [ 0  0  0 36  0]
 [ 0  0  0  0 32]]
accuracy_Naive Bayes: 1.000
precision_Naive Bayes: 1.000
recall_Naive Bayes: 1.000
f1-score_Naive Bayes : 1.000


# create model for Naive Bayes

In [ ]:
import pandas
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
import pickle
model = GaussianNB()
model.fit(X_train, y_train)
# save the model to disk
filename = 'finalized_model.sav'
pickle.dump(model, open(filename, 'wb'))
 
# some time later...
 # load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))

# print(result)


In [ ]:
dataArray = [1,0,0,0,0,1,0,0.582609,0.333333,0.333333]
pred = loaded_model.predict([dataArray])
pred

array([1])

# KNN CLASSIFIER

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=2)
neigh.fit(X_train, y_train)

acc_knn = round(neigh.score(X_train, y_train) * 100, 2)
print(acc_knn)

100.0
